spring.application.name=Blood-Service
server.port=8085
eureka.client.service-url.defaultZone:http://localhost:8761/eureka

management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        register-health-indicator: true
#        sliding-window-type: COUNT_BASED   # or TIME_BASED
#        sliding-window-size: 10            # last 10 calls
#        minimum-number-of-calls: 5         # before CB can calculate failure rate
#        permitted-number-of-calls-in-half-open-state: 3
#        wait-duration-in-open-state: 10s   # how long CB stays OPEN before retrying
#        failure-rate-threshold: 50         # % failures before opening
#        slow-call-rate-threshold: 50       # % slow calls before opening
#        slow-call-duration-threshold: 2s   # what counts as "slow"
#        writable-stack-trace-enabled: true
#    instances:
#      bloodServiceCB:
#        base-config: default
#
#  retry:
#    configs:
#      default:
#        max-attempts: 3
#        wait-duration: 500ms
#        enable-exponential-backoff: true
#        exponential-backoff-multiplier: 2
#        ignore-exceptions:
#          - java.lang.IllegalArgumentException
#    instances:
#      bloodServiceRetry:
#        base-config: default
#
#  ratelimiter:
#    configs:
#      default:
#        limit-for-period: 10      # allow 10 calls per refresh-period
#        limit-refresh-period: 1s  # reset every 1 second
#        timeout-duration: 500ms   # wait max 500ms for a permission
#    instances:
#      bloodServiceRateLimiter:
#        base-config: default
#
#  bulkhead:
#    configs:
#      default:
#        max-concurrent-calls: 10
#        max-wait-duration: 1s
#    instances:
#      bloodServiceBulkhead:
#        base-config: default
#
#  thread-pool-bulkhead:
#    configs:
#      default:
#        max-thread-pool-size: 10
#        core-thread-pool-size: 5
#        queue-capacity: 20
#    instances:
#      bloodServiceTPBulkhead:
#        base-config: default
#
#  timelimiter:
#    configs:
#      default:
#        timeout-duration: 2s
#        cancel-running-future: true
#    instances:
#      bloodServiceTimeLimiter:
#        base-config: default
